### ISSUE TITLE
no supported authentication methods available (server sent publickey)

### ISSUE THREAD

**Issue by sangraikang** [MVladislav/ansible-cis-ubuntu-2204#2]
### Describe the problem

Fresh install of ubuntu 22.04, applied the ansible playbook. After finish, I am not able to ssh in to the server.
"no supported authentication methods available (server sent publickey)"
Seems to be related to 5.4.2?
What is the best method to fix this issue? I have ran usg hardening within Ubuntu and has no issue with the ssh.

### Expected behavior

logged in.

### What is version of application which has the issue?

ubuntu 22.04

### What was the last working version of the application?

ubuntu 22.04

### What type of installation are you running?

OS (setup.py)

### What type of device you use to interact with the application?

OS: [e.g. linux, windows, ios]

### Anything in the logs that might be useful for us?

```txt
Here's a clip of the ssh -v
Authorized uses only. All activity may be monitored and reported.debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/sk/.ssh/id_rsa RSA SHA256:3pKgd4KBSgPZJbeSTA7uBTAA4grtsBEaOGcMACxF5E
debug1: Authentications that can continue: publickey
debug1: Trying private key: /home/sk/.ssh/id_ecdsa
debug1: Trying private key: /home/sk/.ssh/id_ecdsa_sk
debug1: Trying private key: /home/sk/.ssh/id_ed25519
debug1: Trying private key: /home/sk/.ssh/id_ed25519_sk
debug1: Trying private key: /home/sk/.ssh/id_xmss
debug1: Trying private key: /home/sk/.ssh/id_dsa
debug1: No more authentication methods to try.
sk@xxx.xxx.xxx.xxx: Permission denied (publickey).
```

### Additional information

Have tried two fresh install of ubuntu 22.04 on x64 hosts.

**Comment by MVladislav** [comment]
Hi @sangraikang 

Is your problem still persisting? 
Upon a quick inspection, it seems that you are not using a public key when attempting to SSH into the server. By default, SSH is configured for public key authentication, and the logs indicate unsuccessful attempts with the default public keys. 
To resolve this, make sure to provide your public key during the SSH login process.

**Comment by sangraikang** [comment]
Yes I am still having same issue. The public key is used in the remote server under authorized_keys and it was primary login method before the cis hardening and after it is giving the ssh error.

**Comment by MVladislav** [comment]
Hmm, that is strange, never get SSH login problem for a fresh Ubuntu 22.04 installation. 
When I mention SSH usage, I'm referring to whether you provide your key with the `ssh` command using `-i ~/.ssh/...` when attempting to login to the server. 
With the limited information from the logs you provided, it's challenging to pinpoint the location of the problem.

It shouldn't be an issue with `cis_ubuntu2204_rule_5_4_2` as it is disabled by default and when i remember correct 5.4.2 is for different login changes not for SSH one.

Are there any additional details in the logs when you attempt to log in via SSH? 
Can you access the Ubuntu server in any other way and check the logs on the server side?
