### ISSUE TITLE
Partitions of the basic system ?

### ISSUE THREAD

**Issue by BoBBer446** [MVladislav/ansible-cis-ubuntu-2204#4]
### Describe the problem

I keep reading that cis 1 server needs a basic configuration. This also applies to the partitions. However, it is never mentioned here which prerequisites are necessary for this. Do I have to partition beforehand or does the Ansible playbook do this?

### Expected behavior

-

### What is version of application which has the issue?

lastest

### What type of installation are you running?

OS (setup.py)

### What type of device you use to interact with the application?

OS: [e.g. linux, windows, ios]

**Comment by MVladislav** [comment]
The sections marked **'yes'** in the **README table** should ideally be fully implemented, requiring **no further action** as to install ubuntu an run the playbook.
These sections, marked with **'yes'**, have been implemented according to the descriptions provided in the CIS PDF.
For instance, Example **1.1.2.1** for `/tmp` includes a [templates file](https://github.com/MVladislav/ansible-cis-ubuntu-2204/blob/main/templates/system/tmp.mount.j2) that mounts it as specified.

The audit from PDF-section should reflect my current running implementation as example for **1.1.2.1**:
![image](https://github.com/MVladislav/ansible-cis-ubuntu-2204/assets/7400017/967801ac-df88-458a-b3c4-c1c76836332d)

Hope this answers your question.

**Comment by BoBBer446** [comment]
This means that a minimal Ubuntu installation should be carried out that already includes all the necessary partitions.

1. **`/` (root partition)**: The root directory should have its own partition to prevent it from filling up and bringing the system to a halt.

2. **`/boot`**: Contains the kernel and boot loader. A separate `/boot` partition prevents manipulation of the boot process.

3. **`/home`**: User data and configurations. The separation of `/home` increases user data security.

4. **``/var`**: Log files and other variable data. A separate partition for `/var` prevents log files from overflowing the file system.

5. **``/var/log`**: Log files. A further subdivision of `/var` for log files isolates and protects historical data.

6. **`/var/log/audit`**: Audit logs. The separation of audit logs from other log files enables better monitoring and security.

7. **``/tmp`**: Temporary files. A separate partition for `/tmp` with specific mount options increases security.

8. **``/usr`**: System software. A separate partition prevents the modification of system programs and files.

9. **``/opt`**: Optionally installed software. Separation allows additional applications to be isolated.

Ist that right?

Ist there a Cloud-Init template for this or should i create a Basic Installation before i run this playbook?

**Comment by MVladislav** [comment]
> This means that a minimal Ubuntu installation should be carried out that already includes all the necessary partitions.

Depends on your needs, this playbook has nothing todo with partition management.
This playbook runs with all implemented section on a default ubuntu installation.

> Ist there a Cloud-Init template for this or should i create a Basic Installation before i run this playbook?

There should be no difference between Cloud-Init or a basic installation, both have the base ubuntu system and this playbook will configure the implemented section on it.

> /home: User data and configurations. The separation of /home increases user data security.
> ...

If you need any specific partition separation, you need do this manually, this is not done in that playbook.
Any description with **"...Ensure separate partition exists for..."** is not implemented as defined in the **[README table](https://github.com/MVladislav/ansible-cis-ubuntu-2204?tab=readme-ov-file#cis---list-of-recommendations)**
Only `/tmp` is mounted as **tmpfs**.
